version: '3.4'
services:
  uu_logstore-collector:
    network_mode: "bridge"
    image: h-ehqswb38.rg-euc1irrg.uu-os8-dckimgrepo.eu-c-1.cloud.plus4u.net:5000/uu_logstore-collector:latest
    container_name: uu_logstore-collector
    restart: always
    ports:
      - 24224:24224
    environment:
      - UU_LOGSTORE_GRAYLOG_HOST=h-gr4yl0g0.rg-l06570r3.ls.eu-n-1.cloud.plus4u.net
      - UU_LOGSTORE_GRAYLOG_PORT=12201
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"
  mariadb:
    network_mode: host
    image: centos/mariadb
    container_name: mariadb
    restart: always
    depends_on:
      - uu_logstore-collector
    environment:
      MYSQL_ROOT_PASSWORD: "cool_password"
      MYSQL_DATABASE: "waffle"
    volumes:
      - mariadb_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  waffle:
    network_mode: host
    container_name: waffle
    depends_on:
      - mariadb
    image: h-ehqswb38.rg-euc1irrg.uu-os8-dckimgrepo.eu-c-1.cloud.plus4u.net:5000/waffle:0.6.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOST_PARAM: "10.254.2.6"
      DB_USER_PARAM: "root"
      DB_PASS_PARAM: "cool_password"
      DATABASE_PARAM: "waffle"
      SETUP_PARAM: "false"
volumes:
  mariadb_data:
